"""many-to-many relationship updated

Revision ID: 46b5b2c894e3
Revises: af9bde615f10
Create Date: 2024-06-24 16:16:05.830070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46b5b2c894e3'
down_revision: Union[str, None] = 'af9bde615f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_follow_entry_followed_id'), 'follow_entry', ['followed_id'])
    op.create_unique_constraint(op.f('uq_follow_entry_follower_id'), 'follow_entry', ['follower_id'])
    op.add_column('followed_association', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_constraint('fk_followed_association_follow_entry_id_follow_entry', 'followed_association', type_='foreignkey')
    op.create_foreign_key(op.f('fk_followed_association_follow_entry_id_follow_entry'), 'followed_association', 'follow_entry', ['follow_entry_id'], ['followed_id'])
    op.add_column('follower_association', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_constraint('fk_follower_association_follow_entry_id_follow_entry', 'follower_association', type_='foreignkey')
    op.create_foreign_key(op.f('fk_follower_association_follow_entry_id_follow_entry'), 'follower_association', 'follow_entry', ['follow_entry_id'], ['follower_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_follower_association_follow_entry_id_follow_entry'), 'follower_association', type_='foreignkey')
    op.create_foreign_key('fk_follower_association_follow_entry_id_follow_entry', 'follower_association', 'follow_entry', ['follow_entry_id'], ['id'])
    op.drop_column('follower_association', 'id')
    op.drop_constraint(op.f('fk_followed_association_follow_entry_id_follow_entry'), 'followed_association', type_='foreignkey')
    op.create_foreign_key('fk_followed_association_follow_entry_id_follow_entry', 'followed_association', 'follow_entry', ['follow_entry_id'], ['id'])
    op.drop_column('followed_association', 'id')
    op.drop_constraint(op.f('uq_follow_entry_follower_id'), 'follow_entry', type_='unique')
    op.drop_constraint(op.f('uq_follow_entry_followed_id'), 'follow_entry', type_='unique')
    # ### end Alembic commands ###
